version: '3.8'

services:
  # Service 1: The Database
  db:
    image: postgres:15-alpine
    container_name: invoice_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Maps Docker's internal 5432 to Windows port 5433 (avoids conflict)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: The Visual Interface (PgAdmin) so we can see the tables/data in our browser
  pgadmin:
    image: dpage/pgadmin4
    container_name: invoice_db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # PgAdmin web interface
    depends_on:
      - db

volumes:
  postgres_data: